-- Category Long Descriptions (Türkçe, B2B diş hekimi alet satışı odaklı)
-- Hedef: 18 kategori için 250-400 kelime SEO içerik
-- Sorun: Thin content (description boş = SEO zayıflığı)
-- Riski: Düşük (additive content)

SET NAMES utf8mb4;

-- 66: EL ALETLERİ (ana)
UPDATE oc_category_description SET description = '<p>Profesyonel diş hekimliği el aletleri, klinik pratiğinizin omurgasını oluşturur. Raven Dental olarak diagnostik, endodonti, ortodonti, periodonti, implantoloji, cerrahi, protez, restorasyon ve çekim branşlarının tümüne hizmet veren kapsamlı el aleti koleksiyonu sunuyoruz.</p><p>Tüm aletlerimiz <strong>tıbbi paslanmaz çelik (AISI 304/420/440)</strong>, CE belgeli, otoklav uyumludur. ISO 9001 standartlarında üretilmiş; Mani, Hu-Friedy, Dentsply Maillefer, Brasseler, Komet, NSK gibi dünya markalarının yanı sıra Raven üretimi alternatifleri de bulabilirsiniz.</p><h3>Kategori Altı Branşlar</h3><ul><li><strong>Diagnostics:</strong> Sonda, ayna, ekspolatör, pens — muayene ve tanı için</li><li><strong>Endodontics:</strong> K-File, H-File, gutta percha aletleri, lentulo</li><li><strong>Orthodontics:</strong> Tel kesici, ligature cutter, bracket forceps</li><li><strong>Prosthetics:</strong> Spatül, modelaj, ölçü kaşığı, mum bıçağı</li><li><strong>Implantology:</strong> Osteotom, vida sürücü, depth gauge</li><li><strong>Periodontics:</strong> Gracey ve Universal kuretler, sondaj</li><li><strong>Surgery:</strong> Bistüri sapı, hegar portegü, dilator</li><li><strong>Extraction:</strong> Davye, bein elevatör, luksator</li><li><strong>Preservation:</strong> Kondansatör, karver, modelaj aletleri</li><li><strong>Processing:</strong> Tepsi, pinset, yardımcı aletler</li></ul><p><strong>Toptan ve perakende satış</strong>: 10+ alet siparişlerde özel klinik fiyatı. Stoktaki ürünler 24 saat içinde kargo. Ürün sertifikası ve garantisi her sevkiyatla birlikte.</p>'
WHERE category_id=66 AND language_id=2;

-- 72: ELEKTRONİK (ana)
UPDATE oc_category_description SET description = '<p>Diş hekimliği için elektronik cihazlar — aerator, anguldurva, piyasemen ve mikromotor — kliniğinizin tedavi kalitesini doğrudan etkiler. Raven Dental olarak NSK, W&H, Bien-Air, KaVo gibi dünya markalarının orijinal ürünlerini ve Raven üretimi alternatifleri sunuyoruz.</p><h3>Cihaz Tipleri</h3><ul><li><strong>Aerator (Hava Türbini):</strong> 300.000-400.000 rpm, 2 ve 4 çıkışlı, LED veya fiber optik aydınlatmalı modeller</li><li><strong>Anguldurva (Contra-Angle):</strong> 1:1 (restorasyon), 1:5 (endo), 16:1, 20:1 redüksiyonlu seçenekler</li><li><strong>Piyasemen (Düz Başlık):</strong> Cila, finishing, polishing için</li><li><strong>Mikromotor:</strong> 2/4 çıkışlı, brushless seçenekler, implantoloji ve cerrahi modelleri</li></ul><h3>Standartlar</h3><p>Tüm cihazlarımız <strong>EN ISO 7785-1, EN ISO 1797</strong> standartlarına uygun, otoklav (134°C) uyumlu, yedek parça ve servis garantili. Klipsli (push button) veya anahtarlı (wrench) frez tutma sistemleri, tek ve çoklu jet su soğutma seçenekleri mevcut.</p><p><strong>Servis & Yedek Parça:</strong> Türkiye genelinde 2 yıl garanti, 5 yıl yedek parça temini. Bakım ve onarım için yetkili servis ağı.</p>'
WHERE category_id=72 AND language_id=2;

-- 70: SARF (ana)
UPDATE oc_category_description SET description = '<p>Diş hekimliği sarf malzemeleri, kliniğinizin günlük tüketim ihtiyacını karşılar. Raven Dental olarak rubber dam setleri, klempler, frezler, implant vidaları, eldiven, maske ve diğer sterilizasyon-koruma ürünlerini toptan ve perakende sunuyoruz.</p><h3>Kapsam</h3><ul><li><strong>Rubber Dam Sistemleri:</strong> Latex/non-latex set, klempler (kanat, kanat çamur, premolar, molar), forseps, çerçeve</li><li><strong>Endo Sarf:</strong> Gutta percha point, paper point, sement, lentulo</li><li><strong>Restorasyon Sarf:</strong> Bond, etch, kompozit, kondansatör fırça</li><li><strong>Cerrahi Sarf:</strong> Sütur ipliği (3-0, 4-0, 5-0), bistüri ucu</li><li><strong>İmplant Sarf:</strong> Healing abutment, healing screw, impression coping</li><li><strong>Genel Sarf:</strong> Eldiven, maske, tepsi kağıdı, hasta peçeteleri</li></ul><p><strong>Toptan Avantaj:</strong> 1000+ adet sipariş için özel ödeme planları. Aylık tedarik abonelikleri ile %15''''e varan indirim. Stoklu kalemlerde 24 saat kargo, KVKK uyumlu hasta verisi içermeyen ambalaj.</p><p>Tüm sarf ürünlerimiz <strong>CE belgeli, MDR sınıflandırması Class IIa/IIb</strong>, son kullanma tarihi 2+ yıl. Tedarik kaynağı sertifikası talep üzerine sunulur.</p>'
WHERE category_id=70 AND language_id=2;

-- 71: RAVEN CERRAHİ ALETLER (ana)
UPDATE oc_category_description SET description = '<p><strong>Raven Cerrahi Aletleri</strong> — kendi üretimimiz olan profesyonel diş hekimliği el aletleri serisi. Üretici fiyat avantajı, doğrudan satış, %100 kalite garantisi.</p><h3>Neden Raven Markası?</h3><ul><li><strong>Üretici fiyatına satış:</strong> Distribütör marjı yok, %20-40 daha avantajlı</li><li><strong>Tıbbi paslanmaz çelik (AISI 420):</strong> Sertleştirilmiş, korozyon dirençli</li><li><strong>El yapımı:</strong> Pakistan/Türkiye partner üreticilerden, son işlem Türkiye''''de</li><li><strong>CE belgeli:</strong> EN ISO 13485 ve MDR Class I uyumlu</li><li><strong>Otoklav uyumlu:</strong> 134°C buhar sterilizasyonu, korozyon yok</li><li><strong>2 yıl garanti:</strong> Üretim hatalarına karşı tam değişim</li></ul><h3>Ürün Yelpazesi</h3><ul><li>Cerrahi setler (extraction, implant, periodontal)</li><li>Davyeler ve elevatörler</li><li>Gracey ve Universal kuretler</li><li>Endo el aletleri (manuel)</li><li>Ortodonti pensleri</li><li>Steril yardımcı aletler</li></ul><p><strong>Toptan Sipariş:</strong> 10+ alet için klinik fiyatı, 50+ için dental supply firması fiyatı. Bayilik ve distribütör başvuruları için iletişime geçin: <strong>☎ 0552 853 03 99</strong></p>'
WHERE category_id=71 AND language_id=2;

-- 59: DIAGNOSTICS
UPDATE oc_category_description SET description = '<p>Diagnostik (Tanı) Diş Aletleri — diş hekiminin ilk kontrol ve muayene aşamasında kullandığı temel set. Doğru tanı = doğru tedavi.</p><h3>Set İçerikleri</h3><ul><li><strong>Diş Aynası (Mouth Mirror):</strong> 4, 5 nolu, düz ve büyüteçli; otoklav uyumlu paslanmaz çelik sap</li><li><strong>Eksplorer / Sond:</strong> Çift uçlu (No.6, 17, 23), keskin uç ile çürük tespit</li><li><strong>Periodontal Sond:</strong> WHO sondaj (15mm, 0.5mm uç), CPI/PSR sondajı, milimetrik markaj</li><li><strong>College Pensi (Cotton Plier):</strong> Düz veya 45° eğri, kilitlemeli/kilitsiz</li><li><strong>Eksplorer 23/17 set:</strong> Çürük yüzey detayı için</li><li><strong>LED Muayene Cihazları:</strong> Transilluminator, intraoral kamera</li></ul><h3>Kalite Standartları</h3><p>Tüm diagnostik aletlerimiz <strong>AISI 304/410 paslanmaz çelik</strong>, CE belgeli, otoklav (134°C) ve termodezenfeksiyon (90°C) uyumludur. Üretici: Hu-Friedy, Dentsply, Mani veya Raven seçenekleri.</p><p><strong>Klinik Set Önerisi:</strong> Mini set (4 alet), Standart set (8 alet), Premium set (12 alet + transilluminator). Steril paket veya otoklav kaseti ile sipariş edilebilir.</p>'
WHERE category_id=59 AND language_id=2;

-- 68: ENDODONTICS
UPDATE oc_category_description SET description = '<p>Endodonti Aletleri — kanal tedavisinin başarısı doğrudan kullanılan aletin kalitesine bağlıdır. Mani, Dentsply Maillefer, FKG, VDW gibi dünya markalarının orijinal eğelerinden Ni-Ti döner sistemlere geniş yelpaze sunuyoruz.</p><h3>Endo El Aleti Yelpazesi</h3><ul><li><strong>Manuel K-File / H-File:</strong> ISO No.06-No.140, 21mm/25mm/31mm uzunluk, kalibrasyonlu yüzük renkli</li><li><strong>Ni-Ti Döner Eğeler:</strong> ProTaper Universal/Next/Gold, WaveOne, Reciproc Blue, Hyflex EDM</li><li><strong>Gates Glidden Frezleri:</strong> No.1-6 set, paslanmaz çelik / karbid</li><li><strong>Peeso Frezleri:</strong> No.1-6, post hazırlığı için</li><li><strong>Endo Penseti:</strong> Lock veya non-lock, paper point ve gutta percha tutmak için</li><li><strong>Spreader / Plugger:</strong> El veya finger versiyonu, çekme/itme tekniği</li><li><strong>Lentulo:</strong> No.25-40, kanal içine sement göndermek için</li><li><strong>Apek Lokatorları:</strong> Dijital, lityum-ion pil, çoklu frekans</li></ul><h3>Sterilizasyon</h3><p>Tüm endo aletleri <strong>otoklav 134°C</strong> uyumlu. Tek kullanımlık seçenekler de mevcut. Endo motorları için 2:1 / 16:1 redüktör başlık önerilir.</p><p><strong>Klinik Avantajı:</strong> Markalı eğeleri 6''''lı paket halinde alın, %15 indirim. Renkli üst halka ile ISO numarası kolay tanınır, çapraz kullanım hatası önlenir.</p>'
WHERE category_id=68 AND language_id=2;

-- 67: ORTHODONTICS
UPDATE oc_category_description SET description = '<p>Ortodonti El Aletleri — bracket yerleştirme, tel bükümü, bant uygulama ve sökme işlemleri için profesyonel pensetler ve özel aletler. Hu-Friedy, Bien-Air, Dentaurum, GAC gibi dünya markaları yelpazemizde.</p><h3>Pens Çeşitleri</h3><ul><li><strong>Distal End Cutter:</strong> Tel ucunu hastanın yanağını çizmeyecek şekilde kesip tutar</li><li><strong>Ligature Cutter:</strong> İnce tel/ligature için, hassas kesim</li><li><strong>Pin & Ligature Cutter:</strong> Çok amaçlı, kalın/ince kesim</li><li><strong>Weingart Pliers:</strong> Tel sokma ve manipülasyon</li><li><strong>Bird Beak Pliers:</strong> Tel bükmek için (Square, Round)</li><li><strong>Tweed Loop Forming Pliers:</strong> T-loop, omega loop için</li><li><strong>Bracket Holder:</strong> Bracket''''i indirekt yapıştırma için tutar</li><li><strong>Band Pusher / Removing Pliers:</strong> Ortodontik bant uygulama ve sökme</li><li><strong>Mathieu Needle Holder:</strong> Ortodontik ligatür</li></ul><h3>Tel ve Aksesuar</h3><ul><li>NiTi, NiTi-CuNiTi, Beta-Ti, paslanmaz çelik teller (.014 - .021×.025)</li><li>Bracket setleri (Roth, MBT, Damon prescription)</li><li>Ligature wire / elastik ligature</li><li>Apliansa için power chain</li></ul><p><strong>Otoklav Uyumlu:</strong> Tüm pensetlerimiz 134°C otoklav, ultrasonik temizleme ve termodezenfeksiyon uyumludur. Kalem tutucu çentikli kabzalar.</p>'
WHERE category_id=67 AND language_id=2;

-- 65: PROSTHETICS
UPDATE oc_category_description SET description = '<p>Diş Protezi El Aletleri — ölçü, mum modelaj, akrilik trim, articulator çalışmaları ve klinik protez aşamaları için. Hanau, Whip Mix, Hu-Friedy, KerrHawe markaları yanı sıra Raven üretimi alternatifler.</p><h3>Kategoriye Dahil Aletler</h3><ul><li><strong>Ölçü Kaşıkları:</strong> Üst/alt, dişli/dişsiz, paslanmaz çelik veya plastik (tek kullanımlık)</li><li><strong>Mum Bıçakları (Wax Knife):</strong> Le Cron, P.K. Thomas, Beale, Hollenback</li><li><strong>Mum Spatülü:</strong> No.7, No.31 standart, ısı dirençli</li><li><strong>Bunsen / Spirit Lamp:</strong> Mum eritmek için</li><li><strong>Akrilik Trim Aletleri:</strong> Karbid frezler, taşlama uçları</li><li><strong>Articulator:</strong> Plain-line, semi-adjustable, fully-adjustable</li><li><strong>Bench / Lab Bıçakları:</strong> Wax carving için</li><li><strong>Bite Plane / Lucia Jig:</strong> Sentrik kayıt için</li><li><strong>Modelaj Spatülleri:</strong> Cleoid, discoid, Hollenback</li></ul><h3>Protez Çeşitlerine Göre</h3><ul><li>Total protez aletleri</li><li>Parsiyel protez (Kennedy class)</li><li>İmplant üstü protez (abutment maket aletleri)</li><li>Geçici protez (provisional) aletleri</li></ul><p><strong>Otoklav Uyumlu:</strong> Metal aletlerin tümü 134°C otoklava dayanıklıdır. Akrilik ve plastik aletler kimyasal dezenfeksiyon ile temizlenir.</p>'
WHERE category_id=65 AND language_id=2;

-- 64: IMPLANTOLOGY
UPDATE oc_category_description SET description = '<p>Diş İmplantı Cerrahisi Aletleri — Straumann, Megagen, Implant Direct, Nobel Biocare, AnyRidge gibi sistemlere uyumlu cerrahi setler ve yardımcı aletler.</p><h3>Cerrahi Set Bileşenleri</h3><ul><li><strong>Kemik Frezleri (Bone Drill):</strong> Pilot drill (2.0mm), twist drill (2.5-4.0mm), profil drill, summer osteotomes</li><li><strong>İmplant Vida Sürücü Seti:</strong> Hex driver (0.05", 1.25mm, 1.5mm), torque limited 35-50 Ncm</li><li><strong>Osteotom:</strong> Konkav/konveks, summer tekniği, sinüs lifting için</li><li><strong>Depth Gauge / Parallel Pin:</strong> Açı kontrolü ve derinlik ölçümü</li><li><strong>Kemik Genişletici (Bone Expander):</strong> Crestal genişletme için</li><li><strong>Cerrahi Tepsi (Surgical Cassette):</strong> 10-20 cm, otoklav uyumlu, kompartmanlı</li><li><strong>Aspirator Uçları:</strong> Frazier, Yankauer; titanyum / paslanmaz</li><li><strong>Soft Tissue Punch:</strong> 3, 4, 5 mm; flapless cerrahi için</li><li><strong>Bone Tap:</strong> Sıkı kemik için thread pre-cutting</li></ul><h3>Yardımcı Set</h3><ul><li>Implant impression coping, healing abutment, transfer</li><li>Cerrahi şablon (surgical guide) hazırlık aletleri</li><li>Periotom (atravmatik çekim için, implant öncesi)</li></ul><p><strong>Sterilizasyon:</strong> Tüm aletler 134°C otoklav uyumlu, EN ISO 17665-1 standardına göre. Tek kullanımlık seçenekler de mevcut.</p>'
WHERE category_id=64 AND language_id=2;

-- 63: PERIODONTICS
UPDATE oc_category_description SET description = '<p>Periodonti (Diş Eti) Tedavisi Aletleri — kuret, scaler, sond ve diş yüzey temizleme aletleri. Hu-Friedy Gracey serisi başta olmak üzere Brasseler, Nordent ve Raven seçenekleri.</p><h3>Kuret Yelpazesi</h3><ul><li><strong>Gracey Kuretleri (Site-Specific):</strong><ul><li>1/2 (anterior)</li><li>3/4 (anterior + premolar)</li><li>5/6 (premolar)</li><li>7/8, 9/10 (posterior bukkal/lingual)</li><li>11/12 (posterior mesial)</li><li>13/14 (posterior distal)</li><li>15/16, 17/18 (modifiye, derin pocket)</li></ul></li><li><strong>Universal Kuretler:</strong> Columbia 4R/4L, McCall 13/14, Younger-Good 7/8</li><li><strong>Scaler:</strong> Sickle (anterior/posterior), HOE-Pole (kalkulus için)</li><li><strong>Hoe Scaler:</strong> Subgingival kalkulus için</li></ul><h3>Sondaj</h3><ul><li>WHO Probe (Periodontal Screening Record — PSR)</li><li>UNC-15 Probe (milimetrik 15mm)</li><li>Furcation Probe (Naber)</li><li>Williams Probe</li></ul><h3>Bakım & Bileme</h3><p>Periodontal aletler keskinlik gerektiren aletlerdir — düzenli <strong>bileme (sharpening)</strong> şarttır. Arkansas/India taş seti ve bileme rehberlerimiz mevcut. Bileme öncesi/sonrası mikroskop kontrolü önerilir.</p><p><strong>Otoklav:</strong> Tüm metal kuretler 134°C otoklav uyumludur. Kalem tutucu ergonomik kabzalar (silikon ve standart paslanmaz).</p>'
WHERE category_id=63 AND language_id=2;

-- 62: SURGERY
UPDATE oc_category_description SET description = '<p>Diş Cerrahisi Aletleri — gömülü diş çekimi, periodontal flap, apikoektomi, kist eksizyonu ve oral cerrahi vakaları için profesyonel setler.</p><h3>Cerrahi El Aleti</h3><ul><li><strong>Bistüri Sapı (Scalpel Handle):</strong> No.3 (standart), No.4 (büyük), oynar başlık alternatifi</li><li><strong>Bistüri Ucu:</strong> No.10, 11, 12, 15, 15C — tek kullanımlık</li><li><strong>Periosteal Elevator:</strong> Molt 9, Pritchard, Buser; yumuşak doku ayırma için</li><li><strong>Cerrahi Makas:</strong> Iris (eğri/düz), Goldman-Fox, La Grange — yumuşak doku için</li><li><strong>Hegar Portegü (Needle Holder):</strong> 15cm/17cm; Mathieu (yaylı), Crile-Wood</li><li><strong>Sütur Forsepsi:</strong> Adson (dişli/dişsiz), Bonney</li><li><strong>Dilatör:</strong> Yumuşak doku için, kistektomi öncesi</li><li><strong>Curette (Cerrahi):</strong> Lucas, Molt — kemik granül temizliği</li><li><strong>Bone Rongeur (Kemik Kırıcı):</strong> Side cutting, end cutting; Friedman, Blumenthal</li><li><strong>Bone File (Kemik Eğesi):</strong> Soğuk kemik düzeltme</li><li><strong>Aspirator Tip:</strong> Frazier (5F, 8F, 10F), Yankauer</li></ul><h3>Sütur Materyali</h3><ul><li>Vicryl, Monocryl (emilebilir): 3-0, 4-0, 5-0</li><li>İpek (silk): 3-0, 4-0</li><li>Naylon: 5-0, 6-0 (estetik)</li></ul><p><strong>Set Önerisi:</strong> Basic surgery (10 alet), Implant surgery (18 alet), Apikoektomi seti (14 alet). Otoklav uyumlu cerrahi kaseti ile sipariş.</p>'
WHERE category_id=62 AND language_id=2;

-- 61: EXTRACTION (Çekme aletleri)
UPDATE oc_category_description SET description = '<p>Diş Çekim Aletleri — atravmatik çekim için davyeler, elevatörler ve luksatorlar. Doğru alet seçimi: kemik kaybını minimize eder, implant başarısını artırır.</p><h3>Davye Çeşitleri (Forceps)</h3><h4>Üst Çene</h4><ul><li><strong>No.1 / Universal Anterior:</strong> Üst kesici ve kanin</li><li><strong>No.150 / Cryer Universal:</strong> Üst tüm dişler</li><li><strong>No.18L / 18R:</strong> Üst sol/sağ molar (kök ayırıcı)</li><li><strong>No.65:</strong> Üst kök / üçüncü molar</li><li><strong>No.88L / 88R:</strong> Üst çürük molar</li></ul><h4>Alt Çene</h4><ul><li><strong>No.151:</strong> Alt premolar/kesici universal</li><li><strong>No.16 / Cowhorn:</strong> Alt molar (interradiküler çekim)</li><li><strong>No.17:</strong> Alt molar standart</li><li><strong>No.74:</strong> Alt kök</li><li><strong>No.45:</strong> Alt anterior</li></ul><h4>Pedodonti</h4><ul><li>No.1A, 150S, 151S (çocuk diş davyeleri)</li></ul><h3>Elevatörler (Luksatör)</h3><ul><li><strong>Bein Düz Elevatör:</strong> 2mm, 3mm, 4mm, 5mm</li><li><strong>Bein Eğri Elevatör (Mesial/Distal):</strong> Aynı boyutlar</li><li><strong>Heidbrink (Root Pick):</strong> Apikal kök parçaları için</li><li><strong>Apik Forceps:</strong> Köktekleri grub çıkarmak için</li><li><strong>Luksator (Periotom):</strong> 1.5mm, 2mm, 3mm, 4mm — atravmatik (implant öncesi şart)</li><li><strong>Crane / Cogswell:</strong> Tüber çekimi</li></ul><h3>Kalite & Otoklav</h3><p>Tüm davye ve elevatörler <strong>AISI 420 sertleştirilmiş paslanmaz çelik</strong>, 134°C otoklav uyumlu. Kabza ergonomisi: parmak kaymasını önleyen çentikli yüzey.</p>'
WHERE category_id=61 AND language_id=2;

-- 60: PRESERVATION (Restorasyon)
UPDATE oc_category_description SET description = '<p>Restorasyon (Konservatif) Aletleri — dolgu, kompozit restorasyon, amalgam ve cam iyonomer uygulamaları için el aletleri.</p><h3>Kompozit Aletleri</h3><ul><li><strong>Composite Placement:</strong> Plastik veya titanyum kaplı uçlar (TiN), kompozit yapışmaması için</li><li><strong>Hollenback Carver:</strong> No.1, 3 standart, oklüzal şekillendirme</li><li><strong>Cleoid-Discoid Carver:</strong> Pit & fissure detayları</li><li><strong>Composite Brush Set:</strong> Tek kullanımlık, modelaj brushları</li><li><strong>Ball Burnisher:</strong> 1mm-3mm, yüzey parlatma</li></ul><h3>Amalgam Aletleri</h3><ul><li><strong>Amalgam Carrier:</strong> Tek/çift uçlu, klasik veya tabanca tip</li><li><strong>Amalgam Plugger:</strong> 1.0mm, 1.5mm, 2mm; kondansasyon için</li><li><strong>Amalgam Carver:</strong> Hollenback, Ward</li><li><strong>Foiltüp Tutucu (Matrix Retainer):</strong> Tofflemire, sectional matrix</li></ul><h3>Cam İyonomer / Kompomer</h3><ul><li>Specialised plastik spatüller</li><li>Conditioner aplikatörü</li></ul><h3>Yardımcı Aletler</h3><ul><li><strong>Matrix Bands:</strong> Tofflemire, sectional (Palodent, V3)</li><li><strong>Wedges:</strong> Plastik, ahşap; small/medium/large</li><li><strong>Articulating Paper Forceps:</strong> Miller forsepsi</li><li><strong>Plastic Filling Instruments (PFI):</strong> No.1, 2, 3 — özellikle kompozit için</li></ul><h3>Polishing & Finishing</h3><ul><li>Soflex Discs / Cups</li><li>Polishing brushes (silicone)</li><li>Composite polishing kit (Enhance, Astropol)</li></ul><p><strong>Otoklav:</strong> Tüm metal aletler 134°C otoklav uyumlu. TiN kaplı kompozit aletleri ekstra koruma için ultrasonik temizleme sonrası lubricant ile bakım önerilir.</p>'
WHERE category_id=60 AND language_id=2;

-- 69: PROCESSING (Yardımcı / İşlem Aletleri)
UPDATE oc_category_description SET description = '<p>Diş Hekimliği Yardımcı ve İşlem Aletleri — tepsi, pinset, ölçü kaşığı, kaseler ve klinik akışını destekleyen genel kullanım ürünleri.</p><h3>Kapsam</h3><ul><li><strong>Tepsi (Tray):</strong> Standart 28×18cm, mini, küçük; paslanmaz veya plastik</li><li><strong>Otoklav Kaseti:</strong> 8-12-16-20 alet kapasitesi; üst ve alt kapaklı, otoklav uyumlu</li><li><strong>Pinset (Cotton / College):</strong> Pamuk pelet, paper point, gutta percha tutmak için</li><li><strong>Ölçü Kaşığı (Impression Tray):</strong> Üst/alt, dişli/dişsiz, perfore/perforate olmayan</li><li><strong>Yumuşak Doku Pensetleri:</strong> Adson, Bonney, Brunschwig</li><li><strong>Cam Kase (Mixing Bowl):</strong> Alginat, alçı, sement karıştırmak için</li><li><strong>Karıştırma Spatülleri:</strong> Plastik, paslanmaz çelik</li><li><strong>Alkol / Antiseptik Hazne:</strong> Steril paketleme öncesi</li><li><strong>Aspirator Uçları:</strong> Saliva ejector, surgical aspirator, dental backflow preventer</li><li><strong>Mikrofırça (Microbrush):</strong> Bond, adeziv uygulaması için (tek kullanımlık)</li><li><strong>Hasta Peçeteleri ve Bib Clip:</strong> Bib zinciri ile</li></ul><h3>Sterilizasyon Aksesuarları</h3><ul><li>Otoklav poşeti (sterilization pouch), self-sealing, indicator boyalı</li><li>İndikator strip (Class 5 / 6)</li><li>Spore test (haftalık biyolojik test)</li><li>Otoklav rulosu (cassette wrap)</li></ul><p><strong>Toptan Set:</strong> 25 ünitelik klinik açılış paketi mevcut. Sipariş üzerine paket içerikleri özelleştirilebilir.</p>'
WHERE category_id=69 AND language_id=2;

-- 73: Aerator
UPDATE oc_category_description SET description = '<p>Aerator (Hava Türbini, High-Speed Handpiece) — 300.000-400.000 rpm hızında çalışan, kompozit/amalgam çıkarma, kron preparasyonu ve crown removal için temel cihaz. NSK, W&H, Bien-Air, KaVo orijinal ürünleri ve Raven alternatifleri.</p><h3>Modeller</h3><h4>Bağlantı (Coupling)</h4><ul><li><strong>2 Hole (Borden):</strong> Eski stil, daha az yaygın</li><li><strong>4 Hole (Midwest):</strong> Türkiye''''de standart, su+hava+geri akış</li><li><strong>Roto Quick / Multiflex:</strong> NSK/KaVo hızlı bağlantı</li></ul><h4>Frez Tutma (Chuck)</h4><ul><li><strong>Klipsli (Push-Button):</strong> Tek elle frez değişimi, mevcut standart</li><li><strong>Anahtarlı (Wrench):</strong> Daha güvenli kilit, geleneksel</li></ul><h4>Aydınlatma</h4><ul><li><strong>Standart (Aydınlatmasız):</strong> Ekonomi modeli</li><li><strong>LED:</strong> Beyaz/sarı ışık, dahili LED</li><li><strong>Fiber Optik:</strong> Üniteden fiber ile ışık iletimi (eski sistemler için)</li></ul><h4>Kafa Boyutu</h4><ul><li>Mini / Pedodonti: Çocuk hasta, küçük ağız</li><li>Standart: Yetişkin</li><li>Torque: Daha yüksek kesim kuvveti (kron kesimi)</li></ul><h3>Bakım</h3><p>Aerator bakımı: her hasta sonrası dahili sterilizasyon (134°C), haftalık yağlama. Otoklav öncesi mutlaka dış yüzey temizlenir. Yağlama kiti ve servis sözleşmesi yelpazemizde.</p><p><strong>Garanti:</strong> NSK 1 yıl, W&H 2 yıl, Bien-Air 2 yıl, Raven 1 yıl. Yedek parça temini 5 yıl.</p>'
WHERE category_id=73 AND language_id=2;

-- 74: Anguldurva
UPDATE oc_category_description SET description = '<p>Anguldurva (Contra-Angle Handpiece) — mikromotora bağlanan ve farklı redüksiyon oranları sunan başlık. Endo, restorasyon ve implantoloji branşları için.</p><h3>Redüksiyon Oranları</h3><ul><li><strong>1:1 (Standart):</strong> Mikromotor hızını aynı oran ile aktarır; klasik restorasyon, polishing</li><li><strong>1:5 (Hız Artırıcı):</strong> Yüksek hız, kompozit ince işlem, finish — mikromotor 40K rpm ise başlık 200K rpm</li><li><strong>16:1 (Endo Redüktör):</strong> Düşük tork-yüksek kontrol, Ni-Ti döner eğeler için zorunlu</li><li><strong>20:1, 32:1, 100:1 (İmplant Redüktör):</strong> İmplant cerrahisi düşük hız (15-50 rpm), yüksek tork (35-50 Ncm)</li></ul><h3>Önemli Markalar & Modeller</h3><ul><li><strong>NSK:</strong> Ti-Max Z series, S-Max M series, S-Max NL series</li><li><strong>W&H:</strong> Synea Vision (1:5), WS-56/75 (endo), WI-75 LED</li><li><strong>Bien-Air:</strong> CA 1:1, CA 1:5L, EVO.15</li><li><strong>KaVo:</strong> EXPERTtorque, MASTERtorque, INTRAmatic</li></ul><h3>Frez / Kontra-angle Frezleri</h3><p>1:1 ve 1:5 başlıklar için kısa şaft (FG), 16:1 ve üzeri için latch type (RA) veya friction grip uzun frezleri kullanılır. Endo döner eğeler için özellikle FG 19mm uzun şaftlı versiyonlar.</p><p><strong>Bakım:</strong> Her hasta sonrası içsel yağlama, otoklav (134°C). Yedek başlık tavsiyesi: en az 2 adet 1:1, 1 adet 1:5, 1 adet 16:1.</p>'
WHERE category_id=74 AND language_id=2;

-- 75: Piyasemen
UPDATE oc_category_description SET description = '<p>Piyasemen (Straight Handpiece) — mikromotora bağlanan düz başlık, polishing, finishing, akrilik trim ve lab çalışmaları için ideal.</p><h3>Kullanım Alanları</h3><ul><li><strong>Polishing / Cila:</strong> Lastik cila lastiği, fırça, keçe ile kompozit/seramik parlatma</li><li><strong>Akrilik Trim:</strong> Karbid frezler, taşlama uçları ile protez düzeltme</li><li><strong>Onlay / İnlay Hazırlık:</strong> Lab tarafında dış yüzey işleme</li><li><strong>Geçici Restorasyon Düzeltme:</strong> Provisional kron/köprü intraoral düzeltme</li><li><strong>Periferal Cerrahi:</strong> Kemik düzeltme (osseoplasty) için</li></ul><h3>Modeller</h3><ul><li><strong>NSK FX65 / FX25:</strong> Standart düz başlık, 40.000 rpm</li><li><strong>W&H S-11:</strong> 1:1, otoklav uyumlu, ergonomik</li><li><strong>Bien-Air PM 1:1:</strong> İmplantoloji destek</li><li><strong>KaVo INTRAmatic LUX:</strong> LED''li, geleneksel</li></ul><h3>Aksesuar</h3><ul><li><strong>Frez tutma:</strong> HP (Handpiece) şaft, 2.35mm — çoğu lab frezi bu standartta</li><li><strong>Burs Set:</strong> Akrilik trim (karbid), porselen düzeltme (elmas), polishing (silikon)</li><li><strong>Mandrel:</strong> Disc ve fırça tutmak için</li></ul><p><strong>Bakım:</strong> Hava türbinine kıyasla daha az bakım gerektirir. Yine de günlük yağlama ve haftalık derinlemesine temizlik önerilir. Otoklav 134°C uyumludur.</p>'
WHERE category_id=75 AND language_id=2;

-- 76: Micro Motor
UPDATE oc_category_description SET description = '<p>Mikro Motor (Electric Micromotor) — diş ünitesinin standart hava motoruna alternatif elektrikli motor cihazı. Anguldurva ve piyasemen başlıklarıyla kullanılır. Daha sessiz, daha kontrollü tork, otomatik hız ayarı.</p><h3>Tipler</h3><ul><li><strong>2 Çıkışlı Mikromotor:</strong> Tek bir başlık bağlanır — restorasyon kliniği</li><li><strong>4 Çıkışlı Mikromotor:</strong> Birden fazla başlık (su, hava, ışık) — multi-disiplinli klinik</li><li><strong>Brushed (Fırçalı):</strong> Klasik, ekonomik</li><li><strong>Brushless (Fırçasız):</strong> Yüksek dayanıklılık, az bakım, premium</li></ul><h3>Özel Kullanım Mikromotorları</h3><ul><li><strong>Endo Motor:</strong> Reciproc/rotation, integrated apex locator, otomatik geri sarma. Örnek: NSK Endo Mate DT2, Dentsply X-Smart Plus, VDW Gold</li><li><strong>İmplant Motor:</strong> 15-2.000 rpm, tork 5-80 Ncm, peristaltik pompa ile irigasyon. Örnek: NSK Surgic Pro, W&H Implantmed, Bien-Air iChiropro</li><li><strong>Cerrahi Motor:</strong> Apikoektomi, kemik düzeltme</li></ul><h3>Önemli Markalar</h3><ul><li><strong>NSK:</strong> Ti-Max NL400, Volvere i7, Surgic Pro</li><li><strong>W&H:</strong> Implantmed Plus, Elcomed, ChiroPro</li><li><strong>Bien-Air:</strong> iChiropro, MX-i Implant</li><li><strong>Dentsply:</strong> X-Smart Plus, X-Smart IQ</li></ul><h3>Aksesuar</h3><ul><li>Peristaltik pompa (irrigation)</li><li>Foot pedal (kablolu / kablosuz)</li><li>Yedek tüp seti (steril, tek kullanımlık)</li></ul><p><strong>Garanti:</strong> Çoğu marka 2 yıl garanti + 5+ yıl yedek parça desteği. Bakım kiti ve eğitim hizmeti talep üzerine.</p>'
WHERE category_id=76 AND language_id=2;

-- Doğrulama
SELECT category_id, LENGTH(description) AS desc_uzunluk FROM oc_category_description
WHERE language_id=2 ORDER BY category_id;

-- ============================================================================
-- 2026-05-12 UPDATE: BU DOSYA ARTIK KULLANILMAMALI.
-- İçerikte Mani / Hu-Friedy / NSK / Dentsply / W&H / KaVo gibi 3. parti marka isimleri
-- bulunmakta, Raven'i distribütör gibi göstermekte. Yerini analysis/seo-patches/09-category-descriptions-rewrite/update.sql aldı.
-- Yeni dosya: üretici pozisyonu, ISO 9001 + CE + AISI 304/420/440 + otoklav 134°C koruyarak yeniden yazıldı.
-- ============================================================================
